-- MySQL Script generated by MySQL Workbench
-- 2018年04月25日 星期三 20时22分23秒
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema OBD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema OBD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OBD` DEFAULT CHARACTER SET utf8 ;
USE `OBD` ;

-- -----------------------------------------------------
-- Table `OBD`.`manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OBD`.`manager` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `managername` VARCHAR(150) NOT NULL,
  `password` VARCHAR(128) NOT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 0,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_login` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'manager information table';


-- -----------------------------------------------------
-- Table `OBD`.`authority`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OBD`.`authority` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `codename` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `authoritycol_UNIQUE` (`codename` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OBD`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OBD`.`role` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `content` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `content_UNIQUE` (`content` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OBD`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OBD`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `username` VARCHAR(150) NOT NULL,
  `password` VARCHAR(128) NOT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 0,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_login` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'manager information table';


-- -----------------------------------------------------
-- Table `OBD`.`picture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OBD`.`picture` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NULL,
  `name` VARCHAR(255) NULL,
  `address` VARCHAR(255) NULL,
  `GPS` VARCHAR(255) NULL,
  `port_direction` INT(11) NOT NULL COMMENT '端口朝向：\n0：上\n1：下\n2：左\n3：右',
  `zero_port_pos` INT(11) NOT NULL COMMENT '0口位置：\n0：上\n1：下\n2：左\n3：右',
  `port_sort` INT(1) NOT NULL COMMENT '端口排序\n0：顺时针\n1：逆时针',
  `picture_path` VARCHAR(255) NOT NULL,
  `confired_picture_path` VARCHAR(255) NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '端口排序方式\n0：顺时针\n1：逆时针',
  `user_id` INT(11) NULL,
  `manager_id` INT(11) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_picture_user1_idx` (`user_id` ASC),
  INDEX `fk_picture_manager1_idx` (`manager_id` ASC),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC),
  UNIQUE INDEX `manager_id_UNIQUE` (`manager_id` ASC),
  CONSTRAINT `fk_picture_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `OBD`.`user` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `fk_picture_manager1`
    FOREIGN KEY (`manager_id`)
    REFERENCES `OBD`.`manager` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OBD`.`role_has_authority`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OBD`.`role_has_authority` (
  `role_id` INT(11) NOT NULL,
  `authority_id` INT(11) NOT NULL,
  PRIMARY KEY (`role_id`, `authority_id`),
  INDEX `fk_role_has_authority_authority1_idx` (`authority_id` ASC),
  INDEX `fk_role_has_authority_role_idx` (`role_id` ASC),
  CONSTRAINT `fk_role_has_authority_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `OBD`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_has_authority_authority1`
    FOREIGN KEY (`authority_id`)
    REFERENCES `OBD`.`authority` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OBD`.`role_has_manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OBD`.`role_has_manager` (
  `role_id` INT(11) NOT NULL,
  `manager_id` INT(11) NOT NULL,
  PRIMARY KEY (`role_id`, `manager_id`),
  INDEX `fk_role_has_manager_manager1_idx` (`manager_id` ASC),
  INDEX `fk_role_has_manager_role1_idx` (`role_id` ASC),
  CONSTRAINT `fk_role_has_manager_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `OBD`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_has_manager_manager1`
    FOREIGN KEY (`manager_id`)
    REFERENCES `OBD`.`manager` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
